USER_TYPE_ADMIN = 0
USER_TYPE_MANAGER = 1
USER_TYPE_OPS = 2
USER_TYPE_EDITOR = 3
USER_TYPE_CREATOR = 4

USER_STATUS_ACTIVATE = 0
USER_STATUS_INACTIVE = 1

VIDEO_STATUS_TO_BE_CREATED = 0
VIDEO_STATUS_SHOT = 1
VIDEO_STATUS_EDITED = 2
VIDEO_STATUS_TO_BE_RESHOT = 3
VIDEO_STATUS_TO_BE_REEDITED = 4
VIDEO_STATUS_UPLOADED = 5
VIDEO_STATUS_DELETED = 6
